{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: image-admission-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
  - name: trust.hooks.securityenforcement.admission.cloud.ibm.com
    clientConfig:
      service:
        name: {{ template "portieris.name" . }}
        namespace: {{ .Values.namespace }}
        path: "/admit"
      caBundle: {{ .Files.Get "certs/caCert.pem" | b64enc }}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods", "deployments", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
